service: dvst-ai-agent-${env:STAGE}  # Change to your project/service name

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.11  # or python3.11, etc.
  region: us-east-2
  stage: ${env:STAGE}
  memorySize: 128
  timeout: 10
  environment:
    STAGE: ${opt:stage, 'dev'}
    APP_NAME: my-service-name
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs"


package:
  individually: true 
  exclude:
    - ./**
  include:
    
    - src/dist/*


  
functions:
  openai:
    name: dvst-ai-agent-search-lambda-${sls:stage}
    handler: search_lambda.handler
    package: 
      # include:
      #   - src/openai_proxy/*
      artifact: src/dist/search_lambda.zip
    environment:
      TAVILY_API_KEY: ${env:TAVILY_API_KEY}  # Ensure this is set in your environment or secrets

resources:
  Parameters:
    ModelId:
      Type: String
      Default: "amazon.nova-pro-v1:0"  # Change to your desired model ID
    
  Resources:
    AiDvstAgentServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: bedrock.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: Lambda
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: 
                    - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:dvst-ai-agent-search-lambda-${sls:stage}"
          - PolicyName: Bedrock
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "bedrock:InvokeAgent"
                    - "bedrock:ListAgents"
                    - "bedrock:GetAgent"
                    - "bedrock:GetAgentActionGroup"
                    - "bedrock:ListAgentActionGroups"
                    - "bedrock:InvokeAgentWithResponseStream"
                  Resource: "*"
          - PolicyName: NovaModelAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "bedrock:InvokeModel"
                    - "bedrock:ListFoundationModels"
                  Resource: 
                    - !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/${ModelId}"  # Use the ModelId parameter defined above
                    

    AiDvstAgent:
      Type: AWS::Bedrock::Agent
      Properties:
        AgentName: dvst-ai-agent-${sls:stage}
        Description: "AI Agent for driving state data"
        AgentResourceRoleArn: !GetAtt AiDvstAgentServiceRole.Arn
        FoundationModel: !Ref ModelId  # Use the ModelId parameter defined above
        AutoPrepare: true
        Instruction: "You are a real estate assistant. Use tools when necessary to answer user questions."
        ActionGroups:
          - ActionGroupName: web_search
            Description: "Web search action"
            ActionGroupExecutor:
              Lambda:  "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:dvst-ai-agent-search-lambda-${sls:stage}"
            FunctionSchema:
              Functions:
                - Name: web_search
                  Description: "Search the web for public real estate information"
                  Parameters: 
                    query:
                      Type: String
                      Description: "Search query for the web search"
                      Required: true