FROM public.ecr.aws/lambda/python:3.11

# Install OS deps required by Playwright
RUN yum install -y \
    libXcomposite \
    libXcursor \
    libXdamage \
    libXext \
    libXi \
    libXtst \
    alsa-lib \
    atk \
    cups-libs \
    gtk3 \
    ipa-gothic-fonts \
    libdrm \
    libxkbcommon \
    xorg-x11-fonts-100dpi \
    xorg-x11-fonts-75dpi \
    xorg-x11-utils \
    xorg-x11-fonts-cyrillic \
    xorg-x11-fonts-Type1 \
    xorg-x11-fonts-misc \
    xorg-x11-server-utils \
    wget \
    unzip \
    && yum clean all

# Install Python deps
COPY app/requirements.txt .
RUN pip install -r requirements.txt

# Install Playwright browsers
RUN playwright install --with-deps

# Copy handler code
COPY app/ ${LAMBDA_TASK_ROOT}

# Set the handler (module.function)
CMD ["scrapper_lambda.handler"]
